### ISSUE TITLE
Dynamic Shutdown Button stays disabled

### ISSUE THREAD

**Issue by viren-nadkarni** [appknox/irene#202]
Steps to reproduce:
- Start a dynamic scan
- Stop dynamic scan. Button will say 'Shutting down device'
- Go to dashboard home
- Go back the app page
![image](https://cloud.githubusercontent.com/assets/5170829/21339379/cd5f5084-c6a4-11e6-8a15-8cb6a72b144e.png)

Actual result:
Button will still say 'Shutting down device'. Button is enabled only when page is refreshed

Expected result:
Button is enabled when device shutdown is complete, without having the need to refresh the page

**Comment by dhilipsiva** [comment]
I have investigated this. Its not a frontend problem. Its not getting data. Closing this Issues. Closing in the favor of https://github.com/appknox/mycroft/issues/521
