### ISSUE TITLE
UI/UX feedbacks

### ISSUE THREAD

**Issue by yashwin** [appknox/irene#358]
- [x] Terminology in all files(discuss with @prateekpanda for all version or all scans)
- [x] There is no notification that directs that static scan has initiated. 
- [x] Also there should be a guideline for choosing the different types of devices
- [x] After the project is been integrated (the dropdown has to be disabled or removed)
- [x] Following the standard messaging all around the dashboard(make notification as status)
- [x] ~Need to understand the user flow (Users who come on to the platform according to their hierarchy)~
- [x] ~Developers/users who use the platform, need not have to see the billing details. Its related only to the decision makers or the stake holders~
- [x] ~Making it more standard product pricing, where user will have a seamless flow~
- [x] ~Having different dashboard views according to different user hierarchy~
- [x] ~Listing out tasks for each role of user in each step during the scanning~
- [x] ~When new project starts, the grey patch looks odd. Look and feel has to be changed a bit more user-friendly~
- [x] Under paste URL (Small text guideline has to be put, stating “Once URL uploaded the scan process gets initiated)
- [x] If there is one application for scan on the dashboard, there is a lot of un-utilized blank space left in open (Tracking in #401 )
- [x] In listing of the severity of the test cases, having common title “Risks” makes it look more legible
- [x] ~Project result (High, Medium and Low in numbers) and Pie chart representation, rather having separate graphical and numbers. Combining both together makes it more user friendly~
- [x] When Static scan get initiated (Representation countdown timer, just to hint the user about the duration the call) (Tracking in #401 )
- [x] ~If there is a use-case of scan with both phone and tablet (Scanning representation would look good and time saver if it starts sequentially)~
- [x] JIRA integration —> button is pointing toward GitHub (Its too confusing); Suggestion: Having in next block makes it more user friendly
- [x] Once integration with JIRA or GitHUB is completed, instead of revoking “Integration completed” term makes is more clearer.

**Comment by dhilipsiva** [comment]
@yashwin Is this still a valid Issue?

**Comment by yashwin** [comment]
yup @dhilipsiva, let it be here
