### ISSUE TITLE
No way to go back to File page from Project Settings page

### ISSUE THREAD

**Issue by viren-nadkarni** [appknox/irene#375]
When going to Project Settings page from File page
![image](https://cloud.githubusercontent.com/assets/5170829/25649743/beb8954e-2ff5-11e7-9e69-57ebd2dd7cfe.png)

There should be a way to go back to File page.
![image](https://cloud.githubusercontent.com/assets/5170829/25650645/0393aca2-2ffc-11e7-84f6-56149145bccc.png)

**Comment by dhilipsiva** [comment]
I am just noticing some UX issues with this one. Will discuss once we @yashwin is hack here.
