### ISSUE TITLE
Error in Invitation page

### ISSUE THREAD

**Issue by yashwin** [appknox/irene#399]
https://rollbar.com/subho007/Irene/items/128/

**Comment by dhilipsiva** [comment]
@yashwin @subho007 Can we let this be for the moment. Do not want to deal with conflicts. Working on the same piece of code.

**Comment by subho007** [comment]
This is a irene issue not a backend issue. There is one small roblem, just fix that

**Comment by dhilipsiva** [comment]
Yeah Yeah. Irene. I know. That is what I meant. There are changes here as well. Okies. Since its just small - @yashwin
