### ISSUE TITLE
UI Feedback

### ISSUE THREAD

**Issue by yashwin** [appknox/irene#401]
- [x] Risk colours: Critical(Red) & High(Orange)
- [x] Vulnerability Band (remove the background and have thick left border and thin border)
- [x] Definition of CVSS on hover CVSS score
- [x] CVSS Invert colours
- [x] Upload App redesign 
- [x] Replacing Prompt with Modal box and Confirm with Confirm box

**Comment by ChillarAnand** [comment]
![i](https://cloud.githubusercontent.com/assets/4463796/26722502/e2b6ee62-47ad-11e7-9032-8009f8c484f3.png)

Size and position of platform icon looks a bit odd. Can you center/left align it with appropriate size?

**Comment by ChillarAnand** [comment]
![b](https://cloud.githubusercontent.com/assets/4463796/26770913/442ca20a-49d8-11e7-8401-f20ccf4bb8e1.png)

Button alignment is not proper in japanese language.

**Comment by yashwin** [comment]
@ChillarAnand : Can you check the Zoom percentage in your system?

**Comment by yashwin** [comment]
@ChillarAnand Fixed it here : #413, Thank you
