### ISSUE TITLE
Markdown is not rendered as HTML

### ISSUE THREAD

**Issue by viren-nadkarni** [appknox/irene#424]
Issue description (which is in markdown) is displayed as-is, it should be rendered. 

![image](https://user-images.githubusercontent.com/5170829/27369386-543acaba-5675-11e7-9596-7a9ad2f4930c.png)

![image](https://user-images.githubusercontent.com/5170829/27369394-5f05a668-5675-11e7-84b9-862ed1a6f921.png)

**Comment by viren-nadkarni** [comment]
@yashwin I'll need your help fixing this:

![image](https://user-images.githubusercontent.com/5170829/28105549-83fa17fe-66fd-11e7-85ec-9f48e4057286.png)
- remove the `<p>` tags
- indent and display bullets for lists

**Comment by dhilipsiva** [comment]
@viren-nadkarni `indent and display bullets for lists` I can indesnt. But needs UI/LI tags from backend.

**Comment by dhilipsiva** [comment]
Actually, UI/LI will add indent. Will add if that is not enough.

**Comment by viren-nadkarni** [comment]
Fixed. Closing
