### ISSUE TITLE
Enable iOS API scan + Multiple URL endpoints

### ISSUE THREAD

**Issue by viren-nadkarni** [appknox/irene#426]
Support:
- IP addresses
- Comma-separated multiple base URLs
- Special chars in base URL

**Comment by viren-nadkarni** [comment]
@yashwin set this regex for API endpoint validation
```
^(,?(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9]))*$
```

**Comment by dhilipsiva** [comment]
@viren-nadkarni @yashwin What about this: https://github.com/johnotander/domain-regex/blob/master/index.js

**Comment by viren-nadkarni** [comment]
@dhilipsiva looks good, but we also want comma separated addresses/hostnames

**Comment by viren-nadkarni** [comment]
@yashwin in the same branch, can you unhide API scan for iOS

**Comment by yashwin** [comment]
@viren-nadkarni : Ok, I will do it 👍

**Comment by subho007** [comment]
no no, we want seperate field for each API @viren-nadkarni @yashwin @dhilipsiva

**Comment by viren-nadkarni** [comment]
@subho007 not comma-separated?

**Comment by subho007** [comment]
why comma seperated. UI won't look good with comma sperated list. Instead a list will look good

**Comment by viren-nadkarni** [comment]
@subho007 :+1:
@yashwin you'll still have to concatenate and send comma-separated list
