### ISSUE TITLE
Form to fill up details while manual scan is requested 

### ISSUE THREAD

**Issue by yashwin** [appknox/irene#568]
Below are the details which has to be collected before the manual scan is requested 

- Company Name (Auto-fetch)
- APP Name (Auto-fetch)
- Environment of the app
- Minimum OS version (android or iOS)
- What would you like us to do in case some features cannot be accessed or are not live on the 
   application?
     - Proceed with the scan & mention the features that were not scanned in the report. We will 
       rescan it later
     - Halt the scan, contact us & then proceed with the complete application scan.
- Does your application require an account to login ? (y/n)
     - If yes- How many user roles are there? (number)
        -- user role 1
             --- username1 
             --- pass1
             --- username2 
             --- pass2
       -- user role 2
             --- username1 
             --- pass1
             --- username2 
             --- pass2
      
- Point of contact for queries pertaining to manual assessment.
   - name
   - email

- Additional comments (optional)

- Upload Docs

**Comment by SubhamBhattacharjee** [comment]
Can you share me the JSON structure for request payload and and response data.
