### ISSUE TITLE
The chart in both Report and dashboard is inconsistent

### ISSUE THREAD

**Issue by cosmosgenius** [appknox/irene#637]
The chart in both Report and dashboard is inconsistent with the number of issues when we have an overridden issue. Eg. an analysis which was medium was moved to low. This analysis still comes in medium count rather than in low.

Steps to reproduce:
1. Move and existing analysis from <any risk> to low.

Expected:
Low count to increase in Report and Dashboard Chart

Actually:
Count remains same.

**Comment by Praseetha-KR** [comment]
Fixed for report in appknox/mycroft#932 and for dashboard in #638
